### PR TITLE
docs(client): add 'wordLimit' option

### PR DESCRIPTION
**Pull request by Mister-Hope**

### CODE REVIEW

**Comment by Mister-Hope** [comment]
The docs seems not deployed by github actions, so I don't know the deploy logic.

I am assuming the docs is updated after each commit, so I am spliting docs in to this sperate PR.

**Comment by Mister-Hope** [comment]
While adding the new option, I found other problems:

1.  I think marking JavaScript types as`number` `string`  ... intead of `Number` `String` is better. But the docs are mixing them.
2.  ``必要性: `true|false` `` 建议改为 `必填: 是|否`
3. Some of the default values are missing.

If you agree with those above, I will send a PR to fix it. @lizheming

**Comment by Mister-Hope** [comment]
So the docs only updates when releasing a new version? @lizheming

**Comment by lizheming** [comment]
@Mister-Hope Most of config documentation was migrated from valine, and I have not check it. If you have time you can modify it as you said~

**Comment by Mister-Hope** [comment]
> @Mister-Hope Most of config documentation was migrated from valine, and I have not check it. If you have time you can modify it as you said~

A PR has already been sent.

**Comment by lizheming** [comment]
> So the docs only updates when releasing a new version? @lizheming

Docs will be updated by commit trigger, and waline.js.org is the latest version now.

**Pull request merged**
