### PR TITLE
fix(client): use standard api to prevent error on some browsers

### PR DESCRIPTION
**Pull request by Mister-Hope**

### CODE REVIEW

**Comment by Mister-Hope** [comment]
Before merging this PR, I have a question, it seems that waline don't support math equation in markdown.

Then why are we importing related css? Since before my marked pr, `<math>` is not allowed in html.

**Comment by Mister-Hope** [comment]
image

I saw you import katex, but I don't think it's working, Shall I check it?

**Comment by lizheming** [comment]
@Mister-Hope mathjax relate issue https://github.com/lizheming/waline/issues/58. We support mathjax by katex to transform to `<math>` tag. Notice that I have not import katex in the client just because of size limit. So it only works on backend after you post your comment, the preview area can't render MathJaxwell.

**Comment by Mister-Hope** [comment]
Got it. I think we should list this behavior in docs:

- We only support blocks `$$ $$` but not inline `$ $`
- It's not working in preview

**Comment by lizheming** [comment]
@Mister-Hope yeah, it must be good to add the description into doc!

**Comment by Mister-Hope** [comment]
You can merge this now😂

**Pull request merged**
