### PR TITLE
feat: bump marked to v2 and use dompurify to support html

### PR DESCRIPTION
**Pull request by Mister-Hope**

### CODE REVIEW

**Comment by Mister-Hope** [comment]
This PR bump marked to v2. while add `dompurify` to sanitize content to prevent from xss attacks.

This also adds supports to insert html in content. (Be aware of this change)

**Comment by Mister-Hope** [comment]
I did not even finish commenting about this PR 🤣

**Comment by Mister-Hope** [comment]
Still needs some dicussion here. Do you think we need to config `dompurify` to forbid some behavior like setting styles, using certain tags? @lizheming

**Comment by lizheming** [comment]
@Mister-Hope 😄 I have reviewed it and it looks fine for me. I haven't upgrade marked to v2 just because of sanitize feature deprecated in the new version. `dompurify` seems a good replacement.

Before dompurify I used a custom function to make all html escaped to show. It's good that we can save more comment content as much as we can. If `dompurify` have some feature like this, I'll very happy to use it to forbid html tags.

**Comment by Mister-Hope** [comment]
> @Mister-Hope 😄 I have reviewed it and it looks fine for me. I haven't upgrade marked to v2 just because of sanitize feature deprecated in the new version. `dompurify` seems a good replacement.
> 
> Before dompurify I used a custom function to make all html escaped to show. It's good that we can save more comment content as much as we can. If `dompurify` have some feature like this, 

`dompurify` can do many things, 

> I'll very happy to use it to forbid html tags.

What do this means, in my opinion, marked should be used to transform markdown to html, and together with the existing html in markdown. Then being handled by `dompurify`.

My consideration is that we can forbid some tags or attributes or other thing, which do not lead to xss attack, but can insert some annoying behavior. E.g: an autoplayed music or video.

**Comment by Mister-Hope** [comment]
To enhance this, I will add some unit test I can image out to test the behavior, and we can pay attention to users feedback after posting it to new versions.

**Comment by lizheming** [comment]
OK, you can try it. I thought allowlist maybe a good way to allow safe tags and attributes.

**Pull request merged**
